{
 "title": "N8N Base Dashboard",
 "description": "n8n basic metrics dashboard ",
 "tags": [
  "nodejs",
  "n8n"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(nodejs_version_info, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Node.js Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "sum(nodejs_version_info{instance=~\"$instance\"}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Uptime (%)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{app=\"n8n\"}[7d])",
     "legendFormat": "7 days"
    },
    {
     "expr": "avg_over_time(probe_success{app=\"n8n\"}[14d])",
     "legendFormat": "14 days"
    }
   ]
  },
  {
   "title": "Service Uptime",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{app=\"n8n\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Process Restart Times",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(changes(process_start_time_seconds{instance=~\"$instance\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Kubernetes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "CPU Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percentunit", "label": "CPU seconds" }
   ],
   "targets": [
    {
     "expr": "# cpu requests value from kubernetes container\navg(kube_pod_container_resource_requests_cpu_cores{namespace=\"default\", container=\"n8n\"})",
     "legendFormat": "container requests"
    },
    {
     "expr": "# cpu limits value from kubernetes container\navg(kube_pod_container_resource_limits_cpu_cores{namespace=\"default\", container=\"n8n\"})",
     "legendFormat": "container limits"
    },
    {
     "expr": "# container cpu usage\nirate(container_cpu_usage_seconds_total{namespace=\"default\", container=\"n8n\", image!=\"\", container!=\"POD\"}[2m])",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "# container cpu throttling\nirate(container_cpu_cfs_throttled_seconds_total{namespace=\"default\", container=\"n8n\", image!=\"\", container!=\"POD\"}[2m])",
     "legendFormat": "throttled {{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "# memory requests value from kubernetes container\navg(kube_pod_container_resource_requests_memory_bytes{namespace=\"default\", container=\"n8n\"})",
     "legendFormat": "container requests"
    },
    {
     "expr": "# memory limits value from kubernetes container\navg(kube_pod_container_resource_limits_memory_bytes{namespace=\"default\", container=\"n8n\"})",
     "legendFormat": "container limits"
    },
    {
     "expr": "# container memory usage\ncontainer_memory_working_set_bytes{namespace=\"default\", container=\"n8n\", image!=\"\", container!=\"POD\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"default\", pod=~\"n8n-.*\"}[2m]))",
     "legendFormat": "# ⬇️ Web Received Throughput"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"default\", pod=~\"n8n-.*\"}[2m]))",
     "legendFormat": "# ⬆️ Web Transmitted Throughput"
    }
   ]
  },
  {
   "title": "Application",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 13, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "irate(process_cpu_user_seconds_total{instance=~\"$instance\"}[2m]) * 100",
       "legendFormat": "User CPU - {{instance}}"
      },
      {
       "expr": "irate(process_cpu_system_seconds_total{instance=~\"$instance\"}[2m]) * 100",
       "legendFormat": "Sys CPU - {{instance}}"
      }
     ]
    },
    {
     "title": "Event Loop Lag",
     "type": "graph",
     "gridPos": { "h": 7, "w": 11, "x": 13, "y": 7 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "nodejs_eventloop_lag_seconds{instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Process Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 16, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{instance=~\"$instance\"}",
       "legendFormat": "Process Memory - {{instance}}"
      },
      {
       "expr": "nodejs_heap_size_total_bytes{instance=~\"$instance\"}",
       "legendFormat": "Heap Total - {{instance}}"
      },
      {
       "expr": "nodejs_heap_size_used_bytes{instance=~\"$instance\"}",
       "legendFormat": "Heap Used - {{instance}}"
      },
      {
       "expr": "nodejs_external_memory_bytes{instance=~\"$instance\"}",
       "legendFormat": "External Memory - {{instance}}"
      }
     ]
    },
    {
     "title": "Active Handlers/Requests Total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nodejs_active_handles_total{instance=~\"$instance\"}",
       "legendFormat": "Active Handler - {{instance}}"
      },
      {
       "expr": "nodejs_active_requests_total{instance=~\"$instance\"}",
       "legendFormat": "Active Request - {{instance}}"
      }
     ]
    },
    {
     "title": "Heap Total Detail",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "nodejs_heap_space_size_total_bytes{instance=~\"$instance\"}",
       "legendFormat": "Heap Total - {{instance}} - {{space}}"
      }
     ]
    },
    {
     "title": "Heap Used Detail",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "nodejs_heap_space_size_used_bytes{instance=~\"$instance\"}",
       "legendFormat": "Heap Used - {{instance}} - {{space}}"
      }
     ]
    },
    {
     "title": "Heap Available Detail",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "nodejs_heap_space_size_available_bytes{instance=~\"$instance\"}",
       "legendFormat": "Heap Used - {{instance}} - {{space}}"
      }
     ]
    }
   ]
  }
 ]
}